### ISSUE TITLE
transfer files from the created box to the hosting system

### ISSUE THREAD

**Issue by puneetloya** [mwrock/kitchen-vsphere#11]
I am running all the tests on a vsphere provisioned machine using kitchen-vsphere. Is there a way in kitchen to get the result files back, as these files cannot be used with 'synced folders' which can be done on vagrant (vbox) or docker.

**Comment by mwrock** [comment]
Hmm. not sure what result files you are referring to.

**Comment by puneetloya** [comment]
I am using test kitchen to provision a machine on vsphere. So during the verify phase, a test suite is run on the virtual machine. The results of these tests is written on the machine in vsphere. I want the test reports to be written back to system where I run the test-kitchen from.

**Comment by mwrock** [comment]
You would need to use the scp or rbvmomi to copy those files over to the host. I don't think thats something that's something the kitchen driver would implement since grabing those files would not be done via test-kitchen.

**Comment by puneetloya** [comment]
ok I get your point. 

Test-kitchen is for testing the infrastructure scripts. So it does run tests on a vms to check if the chef scripts worked as expected. 

Consider this test kitchen setup (with vsphere) is used in a build system environment. In such cases we would like to keep the results on to the CI-system where as the VMs will be destroyed after the test run.

Another point of view:

If you consider drivers which connect to docker or a Vagrant(vbox) machine, they do have options for synced-folders(kitchen-vagrant) or volume(kitchen-docker) where any log files and results can be retained. I realize they are easier to be implemented as these options just create sym-links between the host (we start test-kitchen on) and docker/vbox machine. 

A feature like 'synced-folders' would be nice to have on kitchen-vsphere.

**Comment by mwrock** [comment]
At CenturyLink where I work, all cookbook commits automatically trigger builds which run kitchen tests on either vsphere or docker depending on the nture of the test. Our build agents log the kitchen console output as build artifacts in the CI server so they are retrievable after VMs and containers have been destroyed. So that is one approach you may take.

Perhaps you are using a different test runner, but serverspec does not store result files on the test instance. Everything is simply dumped to the console which kitchen itself logs on the host in the `.kitchen` folder.

The vagrant and docker kitchen drivers provide no syncing capabilities in the actual driver. Those capabilities come from the underlying docker/vagrant code. Kitchen drivers simply hook into the various kitchen states.

Another thing to be aware of is that this driver is a "legacy driver". All active vsphere kitchen driver development is taking place in [chef-provisioning-vsphere](https://github.com/CenturyLinkCloud/chef-provisioning-vsphere) which includes a kitchen driver. You dont need to be using chef-provisioning` to use its kitchen driver.
